[package]
name = "android"
version = "0.1.0"
edition = "2021"
license = "Zlib"

[dependencies]
jni = "0.21"
android-activity = { workspace = true }
ndk = { workspace = true }
ndk-sys = { workspace = true }
log = { workspace = true }
